In [1]:
#Phishing Domain Detection



In [2]:
#1) Problem Statement 
#The goal of this project is to create and put into practice a machine learning model that can distinguish between legal and phishing domain URLs with accuracy. The model needs to learn to recognize the various traits and patterns that differentiate authentic domains from phishing domains given a dataset of domain URLs.

In [3]:
# 2) Data Collection
#  Dataset Source : https://data.mendeley.com/public-files/datasets/72ptz43s9v/files/26197eb8-15bc-4e06-a269-aa10ddc286f0/file_downloaded

In [4]:
# 2.1 Importing Data And Required Packages

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [22]:
#Import the CSV Data as Pandas DataFrame
df = pd.read_csv("c:\\Users\\neo\\Downloads\\dataset_full.csv")


In [23]:
#Show Top 5 Records
df.head()


qty_dot_url  qty_hyphen_url  qty_underline_url  qty_slash_url  \
0            3               0                  0              1   
1            5               0                  1              3   
2            2               0                  0              1   
3            4               0                  2              5   
4            2               0                  0              0   

   qty_questionmark_url  qty_equal_url  qty_at_url  qty_and_url  \
0                     0              0           0            0   
1                     0              3           0            2   
2                     0              0           0            0   
3                     0              0           0            0   
4                     0              0           0            0   

   qty_exclamation_url  qty_space_url  ...  qty_ip_resolved  qty_nameservers  \
0                    0              0  ...                1                2   
1                    0              0  ...                1                2   
2                    0              0  ...                1                2   
3                    0              0  ...                1                2   
4                    0              0  ...                1                2   

   qty_mx_servers  ttl_hostname  tls_ssl_certificate  qty_redirects  \
0               0           892                    0              0   
1               1          9540                    1              0   
2               3           589                    1              0   
3               0           292                    1              0   
4               1          3597                    0              1   

   url_google_index  domain_google_index  url_shortened  phishing  
0                 0                    0              0         1  
1                 0                    0              0         1  
2                 0                    0              0         0  
3                 0                    0              0         1  
4                 0                    0              0         0  

[5 rows x 112 columns]

In [25]:
#Shape of the dataset
df.shape

(88647, 112)

In [38]:
# 3) Data Checks to Perform 

#Check Missing values
#Check Duplicates
#Check data type
#Check the number of unique values of each column
#Check statistics of data set

In [27]:
# 3.1) Checking for missing values 

df.isna().sum()

qty_dot_url             0
qty_hyphen_url          0
qty_underline_url       0
qty_slash_url           0
qty_questionmark_url    0
                       ..
qty_redirects           0
url_google_index        0
domain_google_index     0
url_shortened           0
phishing                0
Length: 112, dtype: int64

In [32]:
# 3.2) Check Duplicates

df.duplicated().sum()

1438

In [34]:
# since duplicates were identified we drop them

df = df.drop_duplicates()


In [35]:
df.duplicated().sum()

0

In [36]:
# 3.3 Check data types

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87209 entries, 0 to 88646
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 75.2 MB


In [37]:
# 3.4 Checking the number of unique values of each column

df.nunique()

qty_dot_url             23
qty_hyphen_url          30
qty_underline_url       22
qty_slash_url           25
qty_questionmark_url     6
                        ..
qty_redirects           15
url_google_index         3
domain_google_index      3
url_shortened            2
phishing                 2
Length: 112, dtype: int64

In [39]:
for column in df.columns:
    unique_values = df[column].unique()
    print(f"Column: {column}")
    print(unique_values)
    print()


Column: qty_dot_url
[ 3  5  2  4  1  6  9  7  8 10 12 15 11 14 18 16 20 13 17 23 24 19 22]

Column: qty_hyphen_url
[ 0  1  2  4  3  6  5  8  7 12 10  9 19 11 14 17 15 18 13 20 26 25 35 23
 34 24 21 31 16 27]

Column: qty_underline_url
[ 0  1  2  3  5  4 10  7 21  8 16  6  9 17 12 14 19 11 13 15 18 20]

Column: qty_slash_url
[ 1  3  5  0  2  4  6 10  7 12  9 11  8 14 19 16 18 13 17 44 21 22 15 29
 20]

Column: qty_questionmark_url
[0 1 2 3 9 7]

Column: qty_equal_url
[ 0  3  1  4  2  7 12  6  5  8 10 11 17  9 14 13 16 15 23 20]

Column: qty_at_url
[ 0  1  3  4 10  2 43  5 14 12 11 15  7  6  8]

Column: qty_and_url
[ 0  2  3  1  6 11  5  4  7  8  9 15 10 12 13 14 19 17 26 16 22]

Column: qty_exclamation_url
[ 0  1  8  2  5  3  4  9  6 10]

Column: qty_space_url
[0 1 4 9 3 2 7 6]

Column: qty_tilde_url
[0 1 5 3 4 2]

Column: qty_comma_url
[ 0  1  4  3  2  5 11  7]

Column: qty_plus_url
[ 0  2  1  5  4  3  6  9 19  7]

Column: qty_asterisk_url
[ 0  2 14  1 22  8 12 20 10 21  3 19  4  5 60 

In [40]:
# removing columns which have only one unique  value or are constant 

columns_to_remove = ['qty_slash_domain', 'qty_questionmark_domain', 'qty_equal_domain','qty_and_domain','qty_exclamation_domain','qty_space_domain','qty_tilde_domain','qty_comma_domain','qty_plus_domain','qty_asterisk_domain','qty_hashtag_domain','qty_dollar_domain','qty_percent_domain']
df = df.drop(columns=columns_to_remove)


In [42]:
#3.5 Check statistics of data set

df.describe()

qty_dot_url  qty_hyphen_url  qty_underline_url  qty_slash_url  \
count  87209.000000    87209.000000       87209.000000   87209.000000   
mean       2.194189        0.331514           0.115252       1.292688   
std        1.239118        1.126436           0.661569       1.896041   
min        1.000000        0.000000           0.000000       0.000000   
25%        2.000000        0.000000           0.000000       0.000000   
50%        2.000000        0.000000           0.000000       0.000000   
75%        2.000000        0.000000           0.000000       2.000000   
max       24.000000       35.000000          21.000000      44.000000   

       qty_questionmark_url  qty_equal_url    qty_at_url   qty_and_url  \
count          87209.000000   87209.000000  87209.000000  87209.000000   
mean               0.009082       0.206768      0.022383      0.141912   
std                0.111737       0.958605      0.281739      0.929997   
min                0.000000       0.000000      0.000000      0.000000   
25%                0.000000       0.000000      0.000000      0.000000   
50%                0.000000       0.000000      0.000000      0.000000   
75%                0.000000       0.000000      0.000000      0.000000   
max                9.000000      23.000000     43.000000     26.000000   

       qty_exclamation_url  qty_space_url  qty_tilde_url  qty_comma_url  \
count         87209.000000   87209.000000   87209.000000   87209.000000   
mean              0.002993       0.001032       0.003279       0.001582   
std               0.088057       0.073249       0.078767       0.069545   
min               0.000000       0.000000       0.000000       0.000000   
25%               0.000000       0.000000       0.000000       0.000000   
50%               0.000000       0.000000       0.000000       0.000000   
75%               0.000000       0.000000       0.000000       0.000000   
max              10.000000       9.000000       5.000000      11.000000   

       qty_plus_url  qty_asterisk_url  qty_hashtag_url  qty_dollar_url  \
count  87209.000000      87209.000000     87209.000000    87209.000000   
mean       0.002798          0.004610         0.000516        0.001926   
std        0.111661          0.304127         0.062162        0.100549   
min        0.000000          0.000000         0.000000        0.000000   
25%        0.000000          0.000000         0.000000        0.000000   
50%        0.000000          0.000000         0.000000        0.000000   
75%        0.000000          0.000000         0.000000        0.000000   
max       19.000000         60.000000        13.000000       10.000000   

       qty_percent_url   qty_tld_url    length_url  qty_dot_domain  \
count     87209.000000  87209.000000  87209.000000    87209.000000   
mean          0.108441      1.048172     36.468897        1.870621   
std           1.736294      0.256120     46.249869        0.701647   
min           0.000000      0.000000      4.000000        0.000000   
25%           0.000000      1.000000     17.000000        1.000000   
50%           0.000000      1.000000     22.000000        2.000000   
75%           0.000000      1.000000     39.000000        2.000000   
max         174.000000     12.000000   4165.000000       21.000000   

       qty_hyphen_domain  qty_underline_domain  qty_at_domain  \
count       87209.000000          87209.000000   87209.000000   
mean            0.115240              0.000768       0.000011   
std             0.423404              0.032647       0.003386   
min             0.000000              0.000000       0.000000   
25%             0.000000              0.000000       0.000000   
50%             0.000000              0.000000       0.000000   
75%             0.000000              0.000000       0.000000   
max            11.000000              3.000000       1.000000   

       qty_vowels_domain  domain_length  domain_in_ip  server_client_domain  \
count       87209.000000   87209.000000  872

In [43]:
df.shape

(87209, 99)